# Generated by Django 5.2 on 2025-05-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casedetails',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(blank=True, max_length=255, null=True)),
                ('court_name', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('responsible_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('appeal_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'casedetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Claimdetails',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_end_date', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.casedetails')),
            ],
            options={
                'db_table': 'claimdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemdetails',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('auction_notice_url', models.CharField(blank=True, help_text='경매공고 URL', max_length=1000, null=True)),
                ('item_spec_url', models.CharField(blank=True, help_text='매각물건명세서 URL', max_length=1000, null=True)),
                ('status_report_url', models.CharField(blank=True, help_text='현황조사서 URL', max_length=1000, null=True)),
                ('appraisal_url', models.CharField(blank=True, help_text='감정평가서 URL', max_length=1000, null=True)),
                ('item_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('valuation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('item_note', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, max_length=255, null=True)),
                ('court_date', models.DateTimeField(blank=True, null=True)),
                ('auction_failures', models.IntegerField(blank=True, default=0, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.casedetails')),
            ],
            options={
                'db_table': 'itemdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listingdetails',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('list_type', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.casedetails')),
            ],
            options={
                'db_table': 'listingdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partydetails',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('party_type', models.CharField(blank=True, max_length=255, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.casedetails')),
            ],
            options={
                'db_table': 'partydetails',
                'managed': True,
            },
        ),
    ]
