# Generated by Django 5.2 on 2025-05-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_casedetails_claimdetails_itemdetails_listingdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCase',
            fields=[
                ('case_number', models.CharField(help_text='사건번호', max_length=100, primary_key=True, serialize=False)),
                ('case_name', models.CharField(blank=True, help_text='사건명', max_length=255, null=True)),
                ('court_name', models.CharField(blank=True, help_text='법원', max_length=255, null=True)),
                ('filing_date', models.DateField(blank=True, help_text='접수일자', null=True)),
                ('responsible_dept', models.CharField(blank=True, help_text='담당계', max_length=255, null=True)),
                ('claim_amount', models.CharField(blank=True, help_text='청구금액', max_length=255, null=True)),
                ('appeal_status', models.BooleanField(blank=True, default=False, help_text='항고여부', null=True)),
                ('minimum_bid_price', models.CharField(blank=True, help_text='최저입찰가', max_length=255, null=True)),
            ],
            options={
                'db_table': 'auction_case',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='claimdetails',
            name='case',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='case',
        ),
        migrations.RemoveField(
            model_name='listingdetails',
            name='case',
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(help_text='물건번호')),
                ('item_spec_url', models.CharField(blank=True, help_text='매각물건명세서URL', max_length=1000, null=True)),
                ('item_purpose', models.CharField(blank=True, help_text='물건용도', max_length=255, null=True)),
                ('valuation_amount', models.CharField(blank=True, help_text='감정평가액', max_length=255, null=True)),
                ('item_note', models.CharField(blank=True, help_text='물건비고', max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, help_text='물건상태', max_length=255, null=True)),
                ('auction_date', models.DateTimeField(blank=True, help_text='매각기일', null=True)),
                ('auction_failures', models.IntegerField(blank=True, default=0, help_text='유찰횟수', null=True)),
                ('item_image_url', models.URLField(blank=True, help_text='이미지URL', null=True)),
                ('auction_date_1', models.DateTimeField(blank=True, help_text='매각기일 1차', null=True)),
                ('decision_date_1', models.DateTimeField(blank=True, help_text='매각결정기일 1차', null=True)),
                ('auction_date_2', models.DateTimeField(blank=True, help_text='매각기일 2차', null=True)),
                ('decision_date_2', models.DateTimeField(blank=True, help_text='매각결정기일 2차', null=True)),
                ('auction_date_3', models.DateTimeField(blank=True, help_text='매각기일 3차', null=True)),
                ('decision_date_3', models.DateTimeField(blank=True, help_text='매각결정기일 3차', null=True)),
                ('auction_date_4', models.DateTimeField(blank=True, help_text='매각기일 4차', null=True)),
                ('decision_date_4', models.DateTimeField(blank=True, help_text='매각결정기일 4차', null=True)),
                ('case_number', models.ForeignKey(db_column='case_number', help_text='사건번호', on_delete=django.db.models.deletion.CASCADE, to='app.auctioncase')),
            ],
            options={
                'db_table': 'auction_item',
                'managed': True,
                'unique_together': {('item_number', 'case_number')},
            },
        ),
        migrations.CreateModel(
            name='AuctionParty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_type', models.CharField(blank=True, help_text='당사자구분', max_length=100, null=True)),
                ('party_name', models.CharField(blank=True, help_text='당사자명', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, help_text='비고', max_length=255, null=True)),
                ('case_number', models.ForeignKey(db_column='case_number', help_text='사건번호', on_delete=django.db.models.deletion.CASCADE, to='app.auctioncase')),
            ],
            options={
                'db_table': 'auction_party',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClaimDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, help_text='소재지', null=True)),
                ('claim_deadline', models.DateField(blank=True, help_text='배당요구종기일', null=True)),
                ('case_number', models.ForeignKey(db_column='case_number', help_text='사건번호', on_delete=django.db.models.deletion.CASCADE, to='app.auctioncase')),
            ],
            options={
                'db_table': 'claim_distribution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, help_text='소재지', null=True)),
                ('listing_type', models.CharField(blank=True, help_text='목록구분', max_length=100, null=True)),
                ('details', models.TextField(blank=True, help_text='상세내역', null=True)),
                ('final_result', models.CharField(blank=True, help_text='종국결과', max_length=100, null=True)),
                ('final_date', models.DateField(blank=True, help_text='종국일자', null=True)),
                ('case_number', models.ForeignKey(db_column='case_number', help_text='사건번호', on_delete=django.db.models.deletion.CASCADE, to='app.auctioncase')),
            ],
            options={
                'db_table': 'property_listing',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Partydetails',
        ),
        migrations.DeleteModel(
            name='Claimdetails',
        ),
        migrations.DeleteModel(
            name='Itemdetails',
        ),
        migrations.DeleteModel(
            name='Casedetails',
        ),
        migrations.DeleteModel(
            name='Listingdetails',
        ),
    ]
