# Generated by Django 5.2 on 2025-05-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favoriteproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=200)),
                ('court_name', models.CharField(max_length=100)),
                ('filing_date', models.DateField()),
                ('responsible_dept', models.CharField(max_length=100)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('appeal_status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itemdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('item_note', models.TextField(blank=True, null=True)),
                ('item_status', models.CharField(blank=True, max_length=50, null=True)),
                ('valuation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('court_date', models.DateField(blank=True, null=True)),
                ('specification_url', models.URLField(blank=True, help_text='매각물건명세서 URL', max_length=500, null=True)),
                ('status_report_url', models.URLField(blank=True, help_text='현황조사서 URL', max_length=500, null=True)),
                ('appraisal_url', models.URLField(blank=True, help_text='감정평가서 URL', max_length=500, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.case')),
            ],
        ),
    ]
