# Generated by Django 5.2 on 2025-05-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_case_itemdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='case',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Itemdetails',
        ),
    ]
