# Generated by Django 5.1.7 on 2025-03-27 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50)),
                ('item_number', models.IntegerField()),
                ('item_type', models.CharField(max_length=50)),
                ('appraised_price', models.BigIntegerField()),
                ('min_price', models.BigIntegerField()),
                ('bid_method', models.CharField(max_length=50)),
                ('auction_date', models.DateTimeField()),
                ('auction_location', models.CharField(max_length=200)),
                ('address_road', models.CharField(max_length=200)),
                ('address_landlot', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=100)),
                ('officer', models.CharField(max_length=50)),
                ('post_date', models.DateField()),
                ('claim_amount', models.BigIntegerField()),
                ('images', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('schedule_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('min_price', models.BigIntegerField()),
                ('result', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.auctionitem')),
            ],
        ),
    ]
